/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contracts from './contracts'
export type { contracts }
export * as factories from './factories'
export type { Quiz } from './contracts/Quiz'
export { Quiz__factory } from './factories/Quiz__factory'
export type { ERC20 } from './contracts/ERC20'
