/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contracts from './contracts'
export type { contracts }
export * as factories from './factories'
export type { MyToken } from './contracts/MyToken'
export { MyToken__factory } from './factories/MyToken__factory'
export type { Quiz } from './contracts/Quiz'
export { Quiz__factory } from './factories/Quiz__factory'
